#!/bin/bash
#find .git directory
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
git_root=$scriptDir
echo $git_root
while [ ! -e "$git_root/.git" ]; do
    git_root=${git_root%/*}
      if [ "$git_root" = "" ]; then break; fi
done
cd $git_root
if [ -e clang-format ]
then
  rm clang-format
fi
wget https://raw.github.com/SmileXiaofeng/AutoUnitCodeStyle/master/clang-format
chmod +x clang-format
if [ -e clang-format-diff.py ]
then
  rm clang-format-diff.py
fi
wget https://raw.github.com/SmileXiaofeng/AutoUnitCodeStyle/master/clang-format-diff.py
chmod +x clang-format-diff.py
if [ ! -e .clang-format ]
then
  wget https://raw.github.com/SmileXiaofeng/AutoUnitCodeStyle/master/.clang-format
fi
cd ${git_root}/.git/hooks
if [ ! -e pre-commit ]
then
  wget https://raw.github.com/SmileXiaofeng/AutoUnitCodeStyle/master/pre-commit
  chmod +x pre-commit
else  
  echo "#AutoUnitCodeStyle" >> pre-commit
  echo 'scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )' >> pre-commit
  echo 'cd $scriptDir/../..' >> pre-commit
  echo 'git diff --cached | python clang-format-diff.py -i -p1' >> pre-commit
  echo "git add -u" >> pre-commit
fi
cd $scriptDir


