#!/bin/bash

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $scriptDir/../..
pwd
git diff --cached | python clang-format-diff.py -i -p1
git add -u

